// Generates lib/usmap.gen.ts — one SVG path string per US state (+ DC),
// keyed by 2-letter postal code, from us-atlas's pre-projected Albers
// topology (AK/HI insets included, 975x610 viewBox).
//
// Run once (node scripts/gen-usmap.mjs) and commit the output. The three
// packages involved (us-atlas, topojson-client, d3-geo) are devDependencies
// only — nothing map-related ships to the client except these path strings.
import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";
import { feature } from "topojson-client";
import { geoPath } from "d3-geo";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const topo = JSON.parse(
  readFileSync(join(root, "node_modules/us-atlas/states-albers-10m.json"), "utf8")
);

// FIPS → USPS postal code (50 states + DC).
const FIPS_TO_POSTAL = {
  "01": "AL", "02": "AK", "04": "AZ", "05": "AR", "06": "CA", "08": "CO",
  "09": "CT", "10": "DE", "11": "DC", "12": "FL", "13": "GA", "15": "HI",
  "16": "ID", "17": "IL", "18": "IN", "19": "IA", "20": "KS", "21": "KY",
  "22": "LA", "23": "ME", "24": "MD", "25": "MA", "26": "MI", "27": "MN",
  "28": "MS", "29": "MO", "30": "MT", "31": "NE", "32": "NV", "33": "NH",
  "34": "NJ", "35": "NM", "36": "NY", "37": "NC", "38": "ND", "39": "OH",
  "40": "OK", "41": "OR", "42": "PA", "44": "RI", "45": "SC", "46": "SD",
  "47": "TN", "48": "TX", "49": "UT", "50": "VT", "51": "VA", "53": "WA",
  "54": "WV", "55": "WI", "56": "WY",
};

// The topology is pre-projected (Albers USA, 975x610), so render with a
// null projection — geoPath just emits the already-planar coordinates.
const path = geoPath(null);
const { features } = feature(topo, topo.objects.states);

const out = {};
for (const f of features) {
  const postal = FIPS_TO_POSTAL[f.id];
  if (!postal) continue; // skip territories if present
  const d = path(f);
  if (!d) continue;
  // Round coordinates to 1 decimal to keep the generated file small.
  out[postal] = {
    name: f.properties.name,
    d: d.replace(/(\d+\.\d\d+)/g, (m) => Number(m).toFixed(1)),
  };
}

const codes = Object.keys(out).sort();
if (codes.length !== 51) {
  throw new Error(`expected 51 states+DC, got ${codes.length}`);
}

const ts = `// AUTO-GENERATED by scripts/gen-usmap.mjs — do not edit by hand.
// Source: us-atlas states-albers-10m.json (pre-projected AlbersUSA, viewBox 0 0 975 610).
// Regenerate with: node scripts/gen-usmap.mjs

export const MAP_VIEWBOX = "0 0 975 610";

export const STATE_PATHS: Record<string, { name: string; d: string }> = {
${codes.map((c) => `  ${c}: { name: ${JSON.stringify(out[c].name)}, d: ${JSON.stringify(out[c].d)} },`).join("\n")}
};
`;

mkdirSync(join(root, "lib"), { recursive: true });
writeFileSync(join(root, "lib/usmap.gen.ts"), ts);
console.log(`wrote lib/usmap.gen.ts (${codes.length} states, ${(ts.length / 1024).toFixed(0)} KB)`);
